server:
  image: owncloud:9
  links:
    - db
  environment:
    - VIRTUAL_HOST=${host}
  volumes:
    ${host}-apps:/var/www/html/apps
    ${host}-config:/var/www/html/config
    ${host}-data:/var/www/html/data

db:
  image: mariadb:10
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=owncloud
    - MYSQL_PASSWORD=owncloud
    - MYSQL_DATABASE=owncloud
  volumes:
    - ${host}-db:/var/lib/mysql
