.catalog:
  name: "Owncloud"
  version: "9"
  description: "Library service powered by Owncloud"
  uuid: owncloud-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "host"
      label: "Hostname"
      required: true
      default: "cloud.example.com"
      type: "string"

owncloud-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
