.catalog:
  name: Gitlab Community
  version: 8.8.2-0
  description: |
    Gitlab CE is a free GitHub alternative
  minimum_rancher_version: v0.56.0
  maintainer: "David Verholen <david@verholen.com>"
  uuid: gitlab-0
  questions:
    - variable: "host"
      description: "Gitlab Host"
      label: "Hostname"
      required: true
      default: "git.example.com"
      type: "string"
    - variable: "mail"
      description: "Lest Encrypt Mail"
      label: "Mail"
      required: true
      default: "user@domain.tld"
      type: "string"

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
